### ISSUE TITLE
bug: (docker install) can't build image without npm install locally first

### ISSUE THREAD

**Issue by HugoFerrant** [sapphiredev/examples#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

While attempting to build the docker image for production, I encounter an error which stop the build process.
The error is :
```
Step 8/17 : COPY ./package.json package-lock.json /opt/app/
COPY failed: file not found in build context or excluded by .dockerignore: stat package-lock.json: file does not exist
```
And docker is right, the file does not exist. It can be fixed by running a quick `npm install` before building with docker, but it's not written in the readme, and is not intuitive, as we are in a yarn setup.

### Steps To Reproduce

1. Run `sapphire new`
2. Choose the docker setup
3. Choose yarn (both v3 and v2 repro) 
4. Deal with the .env file (even if I don't think it's necessary for the repro)
5. Directly run the `docker build . -t sapphire-sample-bot`
6. See the error at the end

### Expected behavior

Either :
- the readme/doc should mention that a local `npm install` is required before building image
or
- the bug should be fixed (I don't have a clear idea of how, hence this issue instead of a PR. Maybe track the lock file in the git template ?)

**Comment by favna** [comment]
Moved this to the sapphiredev/examples repository as the CLI just pulling code from here

**Comment by HugoFerrant** [comment]
oh sorry, I wasn't aware of this repo ! Thanks

**Comment by HugoFerrant** [comment]
btw I'm as usual available to talk about it on discord if it's simpler for you. @Xelodrin#2858
